### ISSUE TITLE
Error intalling package

### ISSUE THREAD

**Issue by Emmanuel-GD** [hltdi/HornMorpho#2]
I am getting the following error why trying to install HornMorpho version 4

command I used:> pip install H:\HornMorpho\dist\HornMorpho-4.*-py3-none-any.whl
environment :    Windows 10
     wheel installed: 0.37.1
_ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 75, in resolve​
    collected = self.factory.collect_root_requirements(root_reqs)
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 471, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 433, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 295, in __init__
    super().__init__(
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
   dist = self._prepare_distribution()
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 305, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\operations\prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\operations\prepare.py", line 61, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip\_internal\distributions\wheel.py", line 26, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\xxx\anaconda3\envs\cnn1\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file_

**Comment by megasser** [comment]
Hello Amanuel,
The error you're getting seems to be an Anaconda problem since the files that are referenced in the error message are all Anaconda files, unrelated to HornMorpho. I don't use Anaconda with HornMorpho. I guess you ran the 'pip' command within Anaconda?
Michael
________________________________
From: Amanuel Girma ***@***.***>
Sent: Saturday, May 28, 2022 1:22 AM
To: hltdi/HornMorpho ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [hltdi/HornMorpho] Error intalling package (Issue #2)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


I am getting the following error why trying to install HornMorpho version 4

command I used:> pip install H:\HornMorpho\dist\HornMorpho-4.*-py3-none-any.whl
environment : Windows 10
wheel installed: 0.37.1
ERROR: Exception:
Traceback (most recent call last):
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\cli\base_command.py", line 173, in _main
status = self.run(options, args)
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\cli\req_command.py", line 203, in wrapper
return func(self, options, args)
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\commands\install.py", line 315, in run
requirement_set = resolver.resolve(
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\resolution\resolvelib\resolver.py", line 75, in resolve​
collected = self.factory.collect_root_requirements(root_reqs)
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\resolution\resolvelib\factory.py", line 471, in collect_root_requirements
req = self._make_requirement_from_install_req(
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\resolution\resolvelib\factory.py", line 433, in _make_requirement_from_install_req
cand = self._make_candidate_from_link(
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
self._link_candidate_cache[link] = LinkCandidate(
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 295, in init
super().init(
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 156, in init
self.dist = self._prepare()
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
dist = self._prepare_distribution()
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 305, in _prepare_distribution
return self._factory.preparer.prepare_linked_requirement(
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\operations\prepare.py", line 508, in prepare_linked_requirement
return self._prepare_linked_requirement(req, parallel_builds)
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\operations\prepare.py", line 570, in _prepare_linked_requirement
dist = _get_prepared_distribution(
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\operations\prepare.py", line 61, in _get_prepared_distribution
return abstract_dist.get_pkg_resources_distribution()
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\site-packages\pip_internal\distributions\wheel.py", line 26, in get_pkg_resources_distribution
with ZipFile(self.req.local_file_path, allowZip64=True) as z:
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\zipfile.py", line 1267, in init
self._RealGetContents()
File "C:\Users\xxx\anaconda3\envs\cnn1\lib\zipfile.py", line 1334, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
